
import React from 'react';
import { CloseIcon } from './icons/CloseIcon';
import { DownloadIcon } from './icons/DownloadIcon';

interface GeneratedImageModalProps {
  image: { data: string; mimeType: string; };
  prompt: string;
  onClose: () => void;
}

export const GeneratedImageModal: React.FC<GeneratedImageModalProps> = ({ image, prompt, onClose }) => {
  const imageUrl = `data:${image.mimeType};base64,${image.data}`;

  const handleDownload = () => {
    const link = document.createElement('a');
    link.href = imageUrl;
    const extension = image.mimeType.split('/')[1] || 'png';
    link.download = `generated-image-${Date.now()}.${extension}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div 
      className="fixed inset-0 bg-black/70 z-40 flex items-center justify-center p-4"
      onClick={onClose}
      role="dialog"
      aria-modal="true"
      aria-labelledby="image-modal-title"
    >
      <div 
        className="bg-slate-900 border border-slate-700 rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] flex flex-col relative overflow-hidden"
        onClick={e => e.stopPropagation()}
      >
        <div className="p-4 flex justify-between items-center border-b border-slate-800 flex-shrink-0">
          <h2 id="image-modal-title" className="text-lg font-semibold text-yellow-400">Generated Image</h2>
          <button onClick={onClose} className="p-2 rounded-full hover:bg-slate-700 transition-colors" aria-label="Close modal">
            <CloseIcon className="w-6 h-6 text-slate-400" />
          </button>
        </div>
        
        <div className="flex-grow overflow-y-auto p-6 flex flex-col lg:flex-row gap-6">
          <div className="flex-1">
            <img 
              src={imageUrl} 
              alt="Generated by AI" 
              className="rounded-xl w-full h-auto object-contain"
            />
          </div>
          <div className="flex-1 lg:max-w-xs space-y-4">
            <div>
                <h3 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-2">Prompt</h3>
                <p className="text-slate-300 bg-slate-800 p-3 rounded-lg text-sm max-h-48 overflow-y-auto">{prompt}</p>
            </div>
          </div>
        </div>
        
        <div className="p-4 bg-slate-900/50 border-t border-slate-800 flex-shrink-0">
          <button 
            onClick={handleDownload}
            className="w-full flex items-center justify-center gap-2 bg-yellow-500 text-slate-900 font-bold py-3 px-4 rounded-lg hover:bg-yellow-400 transition-colors"
          >
            <DownloadIcon className="w-5 h-5" />
            Download Image
          </button>
        </div>
      </div>
    </div>
  );
};